### ISSUE TITLE
Doker link on README.md is broken

### ISSUE THREAD

**Issue by solvman** [kadena-io/chainweb-mining-client#13]
**_docker pull ghcr.io/kadena-io/chainweb-mining-client:lastest_** link on README.md needs to be fixed. It is broken and doesn't pull anything. It returns:
`Error response from daemon: manifest unknown`

**Comment by MarkCavallo** [comment]
Same issue here.

**Comment by solvman** [comment]
I found the working version here: https://hub.docker.com/r/larsk/chainweb-mining-client

`docker pull larsk/chainweb-mining-client`
