### ISSUE TITLE
Asic miner Setup

### ISSUE THREAD

**Issue by KDAMiner** [kadena-io/chainweb-mining-client#18]
So I'm trying to get away from using a pool to mine. Currently my Asic miner is on poolflare but would rather use my own personal mining client. My problem is your directions are almost impossible to understand. You need to dumb this down with a step by step setup instructions, this would make it extremely helpful.

**Comment by danilobelen** [comment]
Same here, we can use some help!

**Comment by AhmDtimar** [comment]
کمک کردن

**Comment by larskuhtz** [comment]
The README contains more details now about how to use an ASIC miner. An example for a complete compose based setup is available here: https://github.com/kadena-io/docker-compose-chainweb-node/blob/main/mining-node/docker-compose.yaml
