### ISSUE TITLE
cabal couldn't resolve the dependencies

### ISSUE THREAD

**Issue by OverpoweredCoding** [kadena-io/chainweb-mining-client#19]
![image](https://user-images.githubusercontent.com/77810019/147898518-f70e9be9-498f-4135-be79-eb804d76b82b.png)
I'm getting that every time I try to build the file. I've tried in a normal and elevated cmd and I still get the same results.

**Comment by OverpoweredCoding** [comment]
What are the dependencies needed to run this?

**Comment by awfoley** [comment]
I had the same trouble and started going through the code. I bolded what I used, these were noted as tested and working in the revision.

ghc: ['8.8.4', '**8.10.7**', '9.0.1']
cabal: **['3.6']**
os: ['ubuntu-18.04', '**ubuntu-20.04'**, 'macOS-latest']

I have gone through this so many times this is the best I can remember how I did things, but this may help.  It is a huge PITA to make this work.

**Manually install zlib**
sudo apt install zlib1g
sudo apt-get install zlib1g-dev

Check ghc version. ghc -v
You want to use ghc 8.10.7   This may have been installed with cabal... ?

Use **cabal -V** to find out the the version.  You want it to be 3.6.x.x.  I downloaded the binary and moved it to the miner folder.
Binaries - https://www.haskell.org/cabal/download.html
**OR**
To install the latest version from the Git repository, clone the Git repository and then run:
cabal install --project-file=cabal.project.release cabal-install

Lastly,  fron the chainweb-mining-client folder I skipped the cabal build and ran
./cabal run chainweb-mining-client -- -h
cabal built, finished, and ran the miner showing the help information.  I wish this was better, but need to get back to work.  If anyone ones to correct me or can provide this better, please do, I do ask not to put me on blast for missing steps and such.  This is a very loose guide that fried my brain making it work to begin with.

**Comment by OverpoweredCoding** [comment]
Thanks!

**Comment by larskuhtz** [comment]
The supported combinations of operating system, cabal version, and GHC version changes over time. The currently supported combinations can be found in the CI build spec here: https://github.com/kadena-io/chainweb-mining-client/blob/master/.github/workflows/build-application.yml

Other scenarios may work, too, but are not tested.
